# Provide a simple gemspec so you can easily use your
# project in your rails apps through git.
Gem::Specification.new do |s|
  s.name = "gridder"
  s.summary = "CSS Grid System for Rails 3."
  s.description = "Generates stylesheets on the fly, similar to the ones generated by http://960.gs. The main difference is that a namespace is added so that layouts can use multiple grids."
  s.authors = "Stephan Florquin"
  s.email = "stephan.florquin@gmail.com"
  s.homepage = "http://github.com/stephan83/gridder"
  s.files = Dir["lib/**/*"] + ["MIT-LICENSE", "Rakefile", "README.rdoc"]
  s.version = "0.0.1"
end
